import {
  User,
  Service,
  Equipement,
  Produit,
  Lot,
  MouvementStock,
  SortieControlee,
  Maintenance,
  Fournisseur,
  Commande,
  DemandeAllocation,
  Alerte,
  JournalSMS,
  JournalAudit,
} from '../types';

// ==============================================================================
// GESTIONNAIRE DE SECOURS CLIENT (FALLBACK POUR DÉPLOIEMENT STATIQUE NETLIFY DROP)
// ==============================================================================

class ClientMockStore {
  public services: Service[] = [
    { id: 1, code: 'URG', nom: 'Service des Urgences & Réanimation', batiment: 'Bâtiment A', etage: 'RDC' },
    { id: 2, code: 'MAT', nom: 'Maternité & Néonatalogie', batiment: 'Bâtiment B', etage: '1er étage' },
    { id: 3, code: 'PED', nom: 'Pédiatrie & Soins Intensifs Enfants', batiment: 'Bâtiment B', etage: '2e étage' },
    { id: 4, code: 'BLOC', nom: 'Bloc Opératoire Central', batiment: 'Bâtiment C', etage: '1er étage' },
    { id: 5, code: 'LAB', nom: 'Laboratoire d’Analyses Médicales', batiment: 'Bâtiment A', etage: '1er étage' },
    { id: 6, code: 'RAD', nom: 'Radiologie & Imagerie Médicale', batiment: 'Bâtiment A', etage: 'Sous-sol' },
    { id: 7, code: 'PHARM', nom: 'Pharmacie Centrale & Dépôt Stérilisation', batiment: 'Bâtiment D', etage: 'RDC' },
  ];

  public users: User[] = [
    { id: 1, email: 'admin@hgd.cm', nom: 'Mbassi', prenom: 'Samuel', role: 'admin', service_id: null, active: true },
    { id: 2, email: 'logistique@hgd.cm', nom: 'Ngo Bisseck', prenom: 'Chantal', role: 'logistique', service_id: 1, active: true },
    { id: 3, email: 'pharmacie@hgd.cm', nom: 'Dr. Eyenga', prenom: 'Jean-Marc', role: 'pharmacien', service_id: 7, active: true },
    { id: 4, email: 'maintenance@hgd.cm', nom: 'Tchouassi', prenom: 'Gervais', role: 'maintenance', service_id: null, active: true },
    { id: 5, email: 'chef.urgences@hgd.cm', nom: 'Pr. Kamga', prenom: 'Alain', role: 'chef_service', service_id: 1, active: true },
  ];

  public equipements: Equipement[] = [
    {
      id: 1,
      code_inventaire: 'EQ-HGD-URG-001',
      nom: 'Respirateur de Réanimation Dräger Evita V300',
      categorie: 'Réanimation & Ventilation',
      numero_serie: 'DRA-EV3-99482',
      date_acquisition: '2024-03-15',
      statut: 'en_service',
      service_id: 1,
      salle: 'Salle Déchoquage 1',
      garantie_expiration: '2027-03-15',
      etat_lit: 'non_applicable',
      est_archive: false,
      created_at: '2024-03-15T09:00:00Z',
      updated_at: '2026-09-01T10:00:00Z',
    },
    {
      id: 2,
      code_inventaire: 'EQ-HGD-URG-002',
      nom: 'Moniteur Multiparamétrique Philips IntelliVue MX450',
      categorie: 'Monitoring Cardiaque',
      numero_serie: 'PHI-MX45-10293',
      date_acquisition: '2023-11-20',
      statut: 'en_service',
      service_id: 1,
      salle: 'Box Soins Intensifs 3',
      garantie_expiration: '2026-11-20',
      etat_lit: 'non_applicable',
      est_archive: false,
      created_at: '2023-11-20T10:00:00Z',
      updated_at: '2026-09-12T14:30:00Z',
    },
    {
      id: 3,
      code_inventaire: 'LIT-HGD-URG-101',
      nom: 'Lit de Réanimation Motorisé Hill-Rom Progressa',
      categorie: 'Lits d\'hospitalisation',
      numero_serie: 'HIL-PRG-88371',
      date_acquisition: '2024-01-10',
      statut: 'en_service',
      service_id: 1,
      salle: 'Salle Déchoquage 1',
      garantie_expiration: '2027-01-10',
      etat_lit: 'occupe',
      est_archive: false,
      created_at: '2024-01-10T08:00:00Z',
      updated_at: '2026-10-01T09:00:00Z',
    },
    {
      id: 4,
      code_inventaire: 'LIT-HGD-URG-102',
      nom: 'Lit de Réanimation Motorisé Hill-Rom Progressa',
      categorie: 'Lits d\'hospitalisation',
      numero_serie: 'HIL-PRG-88372',
      date_acquisition: '2024-01-10',
      statut: 'en_service',
      service_id: 1,
      salle: 'Box Surveillance Continue',
      garantie_expiration: '2027-01-10',
      etat_lit: 'libre',
      est_archive: false,
      created_at: '2024-01-10T08:00:00Z',
      updated_at: '2026-10-05T11:00:00Z',
    },
    {
      id: 5,
      code_inventaire: 'EQ-HGD-BLOC-003',
      nom: 'Générateur Électrochirurgical Covidien Valleylab FT10',
      categorie: 'Chirurgie & Bloc',
      numero_serie: 'COV-FT10-55421',
      date_acquisition: '2022-06-15',
      statut: 'en_maintenance',
      service_id: 4,
      salle: 'Salle Opératoire 2',
      garantie_expiration: '2025-06-15',
      etat_lit: 'non_applicable',
      est_archive: false,
      created_at: '2022-06-15T09:00:00Z',
      updated_at: '2026-10-04T16:00:00Z',
    },
    {
      id: 6,
      code_inventaire: 'EQ-HGD-RAD-004',
      nom: 'Scanner Hélicoïdal Siemens SOMATOM go.Top 128 coupes',
      categorie: 'Imagerie Lourde',
      numero_serie: 'SIE-SMT-44910',
      date_acquisition: '2021-09-01',
      statut: 'en_service',
      service_id: 6,
      salle: 'Salle Scanner 1',
      garantie_expiration: '2026-09-01',
      etat_lit: 'non_applicable',
      est_archive: false,
      created_at: '2021-09-01T08:00:00Z',
      updated_at: '2026-09-20T10:00:00Z',
    },
    {
      id: 8,
      code_inventaire: 'EQ-HGD-PED-006',
      nom: 'Incubateur Néonatal Hybride Giraffe OmniBed Carestation',
      categorie: 'Néonatalogie',
      numero_serie: 'GIR-OMN-33129',
      date_acquisition: '2022-10-05',
      statut: 'hors_service',
      service_id: 3,
      salle: 'Unité Grands Prématurés',
      garantie_expiration: '2025-10-05',
      etat_lit: 'non_applicable',
      est_archive: false,
      created_at: '2022-10-05T14:00:00Z',
      updated_at: '2026-10-02T08:30:00Z',
    }
  ];

  public produits: Produit[] = [
    {
      id: 1,
      code_cis: 'CIS-6029101',
      designation: 'Morphine Chlorhydrate 10mg/1ml Solution Injectable',
      categorie: 'Antalgiques Majeurs (Stupéfiants)',
      forme_dosage: 'Ampoule 1ml',
      unite_mesure: 'ampoules',
      seuil_alerte: 40,
      est_controle: true,
      temperature_stockage: '15-25°C (Coffre sécurisé)',
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 2,
      code_cis: 'CIS-6029102',
      designation: 'Fentanyl Citrate 0.05mg/ml (50mcg/ml) Ampoules 2ml',
      categorie: 'Anesthésiques Stupéfiants',
      forme_dosage: 'Ampoule 2ml',
      unite_mesure: 'ampoules',
      seuil_alerte: 25,
      est_controle: true,
      temperature_stockage: '15-25°C (Coffre sécurisé)',
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 3,
      code_cis: 'CIS-6104402',
      designation: 'Paracétamol Injectable 10mg/ml Poche 100ml (Perfalgan)',
      categorie: 'Antalgiques & Antipyrétiques',
      forme_dosage: 'Poche IV 100ml',
      unite_mesure: 'poches',
      seuil_alerte: 100,
      est_controle: false,
      temperature_stockage: '15-25°C',
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 4,
      code_cis: 'CIS-6238804',
      designation: 'Amoxicilline + Acide Clavulanique 1g/200mg Poudre Injectable',
      categorie: 'Antibiotiques',
      forme_dosage: 'Flacon poudre IV',
      unite_mesure: 'flacons',
      seuil_alerte: 60,
      est_controle: false,
      temperature_stockage: 'Moins de 25°C',
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 5,
      code_cis: 'CIS-6391001',
      designation: 'Ringer Lactate Soluté de Perfusion 500ml',
      categorie: 'Solutés Massifs & Remplissage',
      forme_dosage: 'Poche 500ml avec tubulure',
      unite_mesure: 'poches',
      seuil_alerte: 80,
      est_controle: false,
      temperature_stockage: '15-25°C',
      created_at: '2025-01-01T00:00:00Z',
    }
  ];

  public lots: Lot[] = [
    {
      id: 1,
      produit_id: 1,
      numero_lot: 'MOR-2026-A12',
      date_peremption: '2026-11-20',
      quantite_initiale: 80,
      quantite_restante: 32,
      prix_unitaire_cfa: 1250,
      statut: 'actif',
      created_at: '2025-01-15T08:00:00Z',
    },
    {
      id: 4,
      produit_id: 3,
      numero_lot: 'PCM-PER-2026-X09',
      date_peremption: '2026-08-15',
      quantite_initiale: 60,
      quantite_restante: 25,
      prix_unitaire_cfa: 650,
      statut: 'perime',
      created_at: '2024-08-10T08:00:00Z',
    },
    {
      id: 5,
      produit_id: 3,
      numero_lot: 'PCM-URG-2026-C01',
      date_peremption: '2026-10-25',
      quantite_initiale: 150,
      quantite_restante: 18,
      prix_unitaire_cfa: 650,
      statut: 'actif',
      created_at: '2024-11-05T09:00:00Z',
    },
    {
      id: 6,
      produit_id: 3,
      numero_lot: 'PCM-SEC-2027-D11',
      date_peremption: '2027-10-01',
      quantite_initiale: 300,
      quantite_restante: 280,
      prix_unitaire_cfa: 650,
      statut: 'actif',
      created_at: '2025-10-05T09:00:00Z',
    },
    {
      id: 9,
      produit_id: 5,
      numero_lot: 'RIN-2027-R50',
      date_peremption: '2027-05-10',
      quantite_initiale: 250,
      quantite_restante: 65,
      prix_unitaire_cfa: 450,
      statut: 'actif',
      created_at: '2025-05-15T09:00:00Z',
    }
  ];

  public sortiesControlees: SortieControlee[] = [
    {
      id: 1,
      registre_numero: 'REG-2026-001',
      produit_id: 1,
      lot_id: 1,
      quantite: 10,
      service_demandeur_id: 4,
      patient_ref_anonyme: 'PAT-HGD-9021',
      medecin_prescripteur: 'Dr. Mbarga (Anesthésiste)',
      motif_therapeutique: 'Protocole analgésie per-opératoire',
      pharmacien_initiateur_id: 3,
      date_initiation: '2026-09-25T10:15:00Z',
      logisticien_validateur_id: 2,
      date_validation: '2026-09-25T14:30:00Z',
      statut: 'approuve',
      hash_registre_inviolable: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    },
    {
      id: 2,
      registre_numero: 'REG-2026-002',
      produit_id: 1,
      lot_id: 1,
      quantite: 5,
      service_demandeur_id: 1,
      patient_ref_anonyme: 'PAT-HGD-9104',
      medecin_prescripteur: 'Pr. Alain Kamga',
      motif_therapeutique: 'Douleur aiguë infarctus du myocarde',
      pharmacien_initiateur_id: 3,
      date_initiation: '2026-10-07T11:20:00Z',
      logisticien_validateur_id: null,
      date_validation: null,
      statut: 'en_attente',
      hash_registre_inviolable: null,
    }
  ];

  public maintenances: Maintenance[] = [
    {
      id: 1,
      equipement_id: 1,
      type: 'preventive',
      priorite: 'haute',
      description_panne: 'Contrôle annuel des capteurs O2 et calibration',
      date_planifiee: '2026-10-20',
      date_realisation: null,
      technicien_id: 4,
      statut: 'planifiee',
      cout_intervention_cfa: 150000,
    },
    {
      id: 2,
      equipement_id: 5,
      type: 'curative',
      priorite: 'urgente',
      description_panne: 'Erreur E-14 plaque neutre',
      date_planifiee: '2026-10-03',
      date_realisation: null,
      technicien_id: 4,
      statut: 'en_retard',
      cout_intervention_cfa: 85000,
    }
  ];

  public alertes: Alerte[] = [
    {
      id: 1,
      type: 'peremption_atteinte',
      niveau: 'critique',
      titre: 'Lot de médicament périmé détecté',
      message: 'Le lot PCM-PER-2026-X09 (Paracétamol Injectable) est périmé depuis le 15/08/2026. Toute sortie est strictement bloquée par FEFO.',
      entite_type: 'lot',
      entite_id: 4,
      est_lu: false,
      created_at: '2026-10-01T08:00:00Z',
    },
    {
      id: 2,
      type: 'stock_bas',
      niveau: 'critique',
      titre: 'Stock critique : Ringer Lactate 500ml',
      message: 'Stock disponible (65 poches) inférieur au seuil d\'alerte minimal fixé à 80 poches.',
      entite_type: 'produit',
      entite_id: 5,
      est_lu: false,
      created_at: '2026-10-06T08:00:00Z',
    }
  ];

  public fournisseurs: Fournisseur[] = [
    {
      id: 1,
      nom: 'Laborex Cameroun S.A.',
      contact_nom: 'M. Paul Atangana',
      telephone: '+237 233 42 15 80',
      email: 'commandes@laborex-cameroun.cm',
      adresse: 'Zone Industrielle de Bassa',
      ville: 'Douala',
      delai_moyen_jours: 3,
      note_fiabilite: 4.8,
      total_commandes: 12,
      total_livrees: 11,
      taux_succes_pct: 92,
      volume_total_cfa: 15400000,
    },
    {
      id: 2,
      nom: 'Biomed Cameroun Technologies',
      contact_nom: 'Ing. Claire Manga',
      telephone: '+237 233 43 78 90',
      email: 'support@biomed-cam.com',
      adresse: 'Rue Prince Bell, Bali',
      ville: 'Douala',
      delai_moyen_jours: 7,
      note_fiabilite: 4.5,
      total_commandes: 8,
      total_livrees: 7,
      taux_succes_pct: 88,
      volume_total_cfa: 28500000,
    },
    {
      id: 3,
      nom: 'UCAM Pharmacie Centrale Grossiste',
      contact_nom: 'Dr. Jean-Pierre Mbida',
      telephone: '+237 222 23 45 67',
      email: 'appro@ucam-sante.cm',
      adresse: 'Boulevard de la Liberté, Akwa',
      ville: 'Douala',
      delai_moyen_jours: 2,
      note_fiabilite: 4.9,
      total_commandes: 20,
      total_livrees: 20,
      taux_succes_pct: 100,
      volume_total_cfa: 34200000,
    }
  ];

  public commandes: Commande[] = [
    {
      id: 1,
      reference: 'CMD-HGD-2026-0041',
      fournisseur_id: 1,
      fournisseur_nom: 'Laborex Cameroun S.A.',
      fournisseur_telephone: '+237 233 42 15 80',
      date_commande: '2026-10-02',
      date_livraison_estimee: '2026-10-08',
      date_reception_reelle: null,
      statut: 'en_attente',
      montant_total_cfa: 2450000,
      cree_par_id: 2,
      createur_nom: 'Chantal Ngo Bisseck',
      commentaires: 'Réapprovisionnement d\'urgence solutés et antalgiques.',
      lignes: [
        { id: 1, designation: 'Ringer Lactate 500ml', quantite: 200, prix_unitaire_cfa: 450 },
        { id: 2, designation: 'Paracétamol Injectable 100ml', quantite: 300, prix_unitaire_cfa: 650 },
      ],
    },
    {
      id: 2,
      reference: 'CMD-HGD-2026-0038',
      fournisseur_id: 2,
      fournisseur_nom: 'Biomed Cameroun Technologies',
      fournisseur_telephone: '+237 233 43 78 90',
      date_commande: '2026-09-15',
      date_livraison_estimee: '2026-09-22',
      date_reception_reelle: '2026-09-21',
      statut: 'livree',
      montant_total_cfa: 12500000,
      cree_par_id: 2,
      createur_nom: 'Chantal Ngo Bisseck',
      commentaires: 'Capteurs d\'oxygène et filtres antibactériens ventilateurs.',
      lignes: [
        { id: 3, designation: 'Cellule O2 Dräger Evita', quantite: 4, prix_unitaire_cfa: 350000 },
      ],
    }
  ];

  public demandesAllocation: DemandeAllocation[] = [
    {
      id: 1,
      service_demandeur_id: 1,
      service_demandeur_nom: 'Service des Urgences & Réanimation',
      chef_service_id: 5,
      chef_service_nom: 'Pr. Alain Kamga',
      type_ressource: 'equipement',
      designation_ressource: 'Respirateur de Transport d\'Urgence',
      quantite: 1,
      justification: 'Augmentation des admissions en détresse respiratoire.',
      urgence: 'urgente',
      statut: 'en_attente',
      traite_par_id: null,
      traite_par_nom: null,
      date_traitement: null,
      date_demande: '2026-10-06T14:30:00Z',
      commentaire_reponse: null,
    },
    {
      id: 2,
      service_demandeur_id: 2,
      service_demandeur_nom: 'Maternité & Néonatalogie',
      chef_service_id: 5,
      chef_service_nom: 'Pr. Alain Kamga',
      type_ressource: 'lit',
      designation_ressource: 'Lit d\'Hospitalisation Maternité',
      quantite: 2,
      justification: 'Pic d\'accouchements gémellaires prévus ce week-end.',
      urgence: 'normale',
      statut: 'approuvee',
      traite_par_id: 2,
      traite_par_nom: 'Chantal Ngo Bisseck',
      date_traitement: '2026-10-07T09:00:00Z',
      date_demande: '2026-10-05T10:00:00Z',
      commentaire_reponse: '2 lits transférés depuis le stock central.',
    }
  ];

  public journalSMS: JournalSMS[] = [
    {
      id: 1,
      destinataire_nom: 'Dr. Jean-Marc Eyenga (Pharmacie)',
      telephone: '+237 699 12 34 56',
      type_alerte: 'PEREMPTION_PROCHE',
      message: '[HGD PHARMACIE] Alerte péremption : Lot PCM-URG-2026-C01 (Paracétamol) périme dans 17 jours.',
      statut_envoi: 'ENVOYÉ_SIMULÉ',
      date_envoi: '2026-10-08T07:00:00Z',
    },
    {
      id: 2,
      destinataire_nom: 'Gervais Tchouassi (Biomed)',
      telephone: '+237 677 89 01 23',
      type_alerte: 'RETARD_MAINTENANCE',
      message: '[HGD BIOMED] Retard maintenance sur Générateur Valleylab (salle Opératoire 2).',
      statut_envoi: 'ENVOYÉ_SIMULÉ',
      date_envoi: '2026-10-08T07:00:00Z',
    }
  ];

  public journalAudit: JournalAudit[] = [
    {
      id: 1,
      utilisateur_id: 1,
      utilisateur_nom: 'Samuel Mbassi',
      role: 'admin',
      action: 'INITIALISATION_SYSTEME',
      entite: 'System',
      entite_id: 'HGD-MEDIGEST-2026',
      details: 'Base de données initialisée avec jeux d\'essais Hôpital Général de Douala.',
      ip_address: '127.0.0.1',
      created_at: '2026-10-08T06:00:00Z',
    },
    {
      id: 2,
      utilisateur_id: 3,
      utilisateur_nom: 'Dr. Jean-Marc Eyenga',
      role: 'pharmacien',
      action: 'INITIATION_SORTIE_CONTROLEE',
      entite: 'SortieControlee',
      entite_id: '2',
      details: 'Initiation sortie 5 ampoules de Morphine pour PAT-HGD-9104.',
      ip_address: '192.168.1.45',
      created_at: '2026-10-07T11:20:00Z',
    }
  ];

  public settings: Record<string, any> = {
    seuil_peremption_proche_jours: 90,
    seuil_peremption_critique_jours: 30,
    email_alertes_actif: true,
    sms_simulation_actif: true,
    email_destinataire_principal: 'direction-medicale@hgd-douala.cm',
    fefo_strict_mode: true,
  };
}

export const clientMockStore = new ClientMockStore();
